### ISSUE TITLE
Can i use it for real time detection with local webcam ？

### ISSUE THREAD

**Issue by Stephenfang51** [kriyeng/yolo-on-colab-notebook#1]
As mentioned
of course on Colab with local webcam !

Thank you !

**Comment by kriyeng** [comment]
I haven't done ever, but maybe this post can help you.

[How to use cap = cv2.VideoCapture(0) in Google Colab](https://stackoverflow.com/questions/54389727/how-to-use-cap-cv2-videocapture0-in-google-colab)

**Comment by Stephenfang51** [comment]
> I haven't done ever, but maybe this post can help you.
> 
> [How to use cap = cv2.VideoCapture(0) in Google Colab](https://stackoverflow.com/questions/54389727/how-to-use-cap-cv2-videocapture0-in-google-colab)

Thanks for suggestion !
I will check it !

**Comment by Varshul** [comment]
Hey @Stephenfang51 did this work?

We are looking to make real time detection in colab for Openpose model. Please help out if you found a solution for the same.

**Comment by Stephenfang51** [comment]
@Varshul 

Hey I didn't try out since it's unpractical, you may use embedding device such as jetson nano to do.
Since you got a lot to work on..... colab is just for fun.

Thanks !
