### ISSUE TITLE
can't save backup, the space in "My Drive" is not recognized

### ISSUE THREAD

**Issue by ragutierrez** [kriyeng/yolo-on-colab-notebook#2]
I'm trying to train YOLO, but when 100 iterations reached, this message shows:

`Can't save to '/content/gdrive/My\Drive/darknet/backup/yolov3-last.weights'`

As you can see, the space is deleted but in my data file I set backup like this:

`backup =  /content/gdrive/My\ Drive/darknet/backup/yolov3-last.weights`

NOTE: now I'm saving the backups to colab and manually downloading them

**Comment by kriyeng** [comment]
Hi @ragutierrez!
Did you cloned darknet from the correct branch using my repo as suggested in the notebook?

Anyway, I highly recommend to use symbolic link for the GDrive paths. I added an update to my tutorial about that, but maybe this repo has no this update. 

You can create a symbolic link to GDrive after mounting it. Like this:

```
# Adding symbolic link
!ln -s "/content/gdrive/My Drive/darknet/" /darknet
```

Then the paths `/content/gdrive/My\ Drive/darknet/backup/yolov3-last.weights` can be converted to `/darknet/backup/yolov3-last.weights`

If you apply this, remember to change the paths on all your config files, obj.data, train.txt, etc

Good luck on your training!

**Comment by ragutierrez** [comment]
I was using the original one, the symbolic link is a good suggestion and the solution.
Thanks and good luck to you too!
