### ISSUE TITLE
Darknet is not able to read train.py

### ISSUE THREAD

**Issue by Shruthi-Sampathkumar** [kriyeng/yolo-on-colab-notebook#3]
Hi.

I am using colab to train darknet. When I run the detector command, it is not able to read the path to train.txt file because it has white spaces in it. I tried using "Shared\ drives" as well, but it is still not working. It would be really helpful if you could help me solve this issue.

Thanks.

Error : Loading weights from darknet53.conv.74...Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Couldn't open file: /content/drive/Shared\drives/darknet/train.txt

**Comment by mehio** [comment]
check if the obj.data has correct paths.

**Comment by kriyeng** [comment]
Hi @Shruthi-Sampathkumar!

If you still have the problem you could try to use symbolic links instead.

```
!ln -s "/content/gdrive/My Drive/darknet/" /myfolder
```

And from now on, you can set your path to your Drive folder as `/myfolder`
