### ISSUE TITLE
Graph?

### ISSUE THREAD

**Issue by muraceous** [kriyeng/yolo-on-colab-notebook#4]
Hi, I just finished training Yolo v3 with my dataset. Is there anyway that I can get or generate a graph of the results?

![image](https://user-images.githubusercontent.com/54627544/63853758-19836c00-c9ce-11e9-8aac-78d4dd00e12a.png)

**Comment by kriyeng** [comment]
Hi Muraceous!

I think it's not possible to plot in the Colab directly from darknet,
but I'm not totally sure about it.

Darknet can plot your training progress if you use it for training in your
local computer, but I think it can't in the colab environment.

Thank you!
David
