### ISSUE TITLE
cat: /usr/local/cuda/include/cudnn.h: No such file or directory

### ISSUE THREAD

**Issue by jhlee0801** [kriyeng/yolo-on-colab-notebook#5]
I am a mac user and trying to follow your guide to train yolov3 with my dataset.
I face a problem during installing cuDNN. I used exactly the same code as below.

!tar -xzvf gdrive/My\ Drive/darknet/cuDNN/cudnn-10.0-linux-x64-v7.5.0.56.tar -C /usr/local/
!chmod a+r /usr/local/cuda/include/cudnn.h

Then I got an Error:
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
chmod: cannot access '/usr/local/cuda/include/cudnn.h': No such file or directory

How could I fix this problem?

**Comment by jay-master** [comment]
It was my stupid mistake. I didn't change the runtime type to GPU. I'm sorry to make you confusing.

**Comment by jhlee0801** [comment]
Problem resolved. The file should be in form of .tgz.
